#!/bin/bash

# Credit to https://github.com/Kloadut/dokku-md-plugin/blob/master/commands
# as this outlines the basic format followed by this plugins operations.
set -e; 

# Check if solr namespace and if so set APP/PLUGIN
if [[ $1 == solr:* ]]; then
	if [[ -z $2 ]]; then
		echo "An app name must be specified"
		exit 1
	else
		APP="$2"
		if [[ -d "/home/git/$APP" ]]; then
			APP_EXISTS=true
		else
			APP_EXISTS=false
		fi
	fi
fi

case "$1" in
	solr:create)
		SOLR_IMAGE=solr/$APP
		IMAGE=$(docker images | grep "foldr/solr" | awk '{print $3}')
		if [[ .z $IMAGE ]]; then
			echo "Solr image not found. Please run 'dokku plugins-install'"
			exit 1
		fi
		if [[ -d "/var/lib/docker/volumes/solr-$APP" ]]; then
			VOLUME="/var/lib/docker/volumes/solr-$APP/layer:/var/lib/solr"
			echo ""
			echo "-----> Reusing solr/$APP"
		else
			VOLUME="/var/lib/solr"
		fi

		# Stop existing container with db
		ID=$(docker ps | grep "$SOLR_IMAGE":latest | awk '{print $1}')
		if [[ ! -z "$ID" ]]; then
			docker stop $ID > /dev/null
		fi

		# Fork image
		ID=$(docker run -d foldr/solr exit 0)
		docker wait $ID > /dev/null
		IMAGE=$(docker commit $ID)
		docker tag $IMAGE $SOLR_IMAGE

		# Launch container
		ID=$(docker run -v $VOLUME -p 9200 -d $SOLR_IMAGE)
		sleep 4

		# Rename persitent volume
		if [[ ! -d "/var/lib/docker/volumes/solr-$APP" ]]; then
			VOLUME_PATH=$(docker inspect $ID | grep "/var/lib/docker/volumes/" | awk '{print $2}' | sed -e "s/\/layer//" | sed -e's/"//g')
			mv $VOLUME_PATH "/var/lib/docker/volumes/solr-$APP"
			sleep 1
		fi

		# Link to app
		dokku solr:link $APP $APP
		echo
		echo "-----> Solr container created: ${SOLR_IMAGE}"
		sleep 1
		dokku solr:info $APP
		;;

	solr:delete)
		SOLR_IMAGE=solr/$APP
	
		# stop container
		ID=$(docker ps -a | grep "$SOLR_IMAGE":latest | awk '{print $1}')
		if [[ ! -z $ID ]]; then
			docker stop $ID
		fi
		
		# remove image
		IMAGE=$(docker images | grep "$SOLR_IMAGE " | awk '{print $1}')
		if [[ ! -z $IMAGE ]]; then
			docker rmi $IMAGE
		fi
		echo
		echo "-----> Solr container deleted: $SOLR_IMAGE"
		;;

	solr:info)
		SOLR_IMAGE=solr/$APP
		ID=$(docker ps -a | grep "$SOLR_IMAGE":latest | awk '{print $1}')
		IP=$(docker inspect $ID | grep IPAddress | awk '{print $2}' | tr -d ',"')
		PORT=$(docker port $ID 8983)
		echo
		echo "        Host: $IP"
		echo "        Port: $PORT"
		echo
		;;

	solr:link)
		echo " CURRENTLY NOT AVAILABLE"
		;;

	solr:logs)
		SOLR_IMAGE=solr/$APP
		ID=$(docker ps -a | grep "$SOLR_IMAGE" | awk '{print $1}')
		docker logs $ID | tail -n 100
		;;

	solr:install)
		SOLR_IMAGE=solr/$APP
		# if the image isn't running then start it
		# once the application is running call `/usr/share/elasticsearch/bin/plugin -install mobz/elasticsearch-head`
		#ID=$(docker ps -a | grep "$ES_IMAGE" | awk 

	help)
		echo "solr:create <app>                   creates a new solr instance"
		echo "solr:delete <app>                   (unlink?)"
		echo "solr:info <app>                     displays details about the solr container"
		echo "solr:link <app>                     bind an app container to another"
		echo "solr:logs <app>                     output the last 100 logs for the container"
		echo "solr:list <app>                     list installed plugins"
		;;

esac